import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import localFont from "next/font/local";

import { afterAuthPath, clerkAppearance, signInPath, signUpPath } from "@/lib/clerk-appearance";

import "@xyflow/react/dist/style.css";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/geist-latin.woff2",
  variable: "--font-geist-sans",
});

const geistMono = localFont({
  src: "./fonts/geist-mono-latin.woff2",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={clerkAppearance}
      signInFallbackRedirectUrl={afterAuthPath}
      signInForceRedirectUrl={afterAuthPath}
      signInUrl={signInPath}
      signUpFallbackRedirectUrl={afterAuthPath}
      signUpForceRedirectUrl={afterAuthPath}
      signUpUrl={signUpPath}
    >
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} dark h-full antialiased`}
      >
        <body className="min-h-full w-full">{children}</body>
      </html>
    </ClerkProvider>
  );
}
